version: '2'

services:
  stargate:
    image: stargateio/sgv2-coordinator-4_0:v2.0.0-ALPHA1-SNAPSHOT
    networks:
      - backend
    ports:
      - 9045:9042
      - 8080:8080
      - 8081:8081
      - 8084:8084
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=c4-${CASSTAG}-cluster
      - CLUSTER_VERSION=4.0
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true
      - DEVELOPER_MODE=true
  stargate-restapi:
    image: stargateio/sgv2-restapi:v2.0.0-ALPHA1-SNAPSHOT
    depends_on:
      - stargate
    networks:
      - backend
    ports:
      - 8082:8082
      - 8088:8088
    mem_limit: 2G
    environment:
      - STARGATE_GRPC_HOST=stargate
      - STARGATE_GRPC_PORT=8090
      - STARGATE_REST_PORT=8082
networks:
  backend:
